title: "eerio: field report"
author:
  name: Paweł Balawender
  email: p.balawender at mimuw edu pl
description: A collection of things I found on the internet :)

remote_theme: jekyll/minima
minima:
  skin: dark

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
