title: "eerio: field report"
author:
  name: eerio
  email: pbalawender101@gmail.com
description: Posts about things I got interested in. And a collection of things I found on the internet :)
github_username: eerio

remote_theme: jekyll/minima
minima:
  skin: dark
